---

computername: dbmacm2
hostname: dbmacm2

finder_proxy_icon_hover_delay: 0

system_save_application_state_on_quit: no
system_expand_save_panel_by_default: yes
system_expand_print_panel_by_default: yes
system_show_file_extensions_warning: no
system_warn_before_emptying_the_trash: yes
system_use_f_keys_as_standard_function_keys: yes
system_index_network_storage_with_spotlight: no
trackpad_tap_to_click: yes

screensaver_ask_for_password: no
screensaver_ask_for_password_in_seconds: 5

shell_path: /usr/local/bin/zsh

homebrew_taps:
  - homebrew/core
#  - cloudflare/cloudflare
#  - homebrew/cask
#  - homebrew/cask-drivers
#  - homebrew/cask-fonts
#  - homebrew/cask-versions
#  - hudochenkov/sshpass
#  - aws/tap

homebrew_apps:
  - alt-tab
  - google-chrome
  - joplin
  - netnewswire
  - slack
  - visual-studio-code
  - zerotier-one
#  - appcleaner
#  - cleanmymac
#  - cleanshot
#  - clipy
#  - licecap
#  - onedrive
#  - postico
#  - postman
#  - shottr
#  - spotify

homebrew_packages:
  - jq
  - lastpass-cli
  - mas
  - pipenv
#  - awscli
#  - check-jsonschema
#  - cloudflared
#  - curl
#  - docker
#  - git
#  - gitlab-runner
#  - gradle
#  - kubectl
#  - ledger
#  - openssh
#  - rsync
#  - shellcheck
#  - sshpass
#  - terraform
#  - vim
#  - wget

mas_apps:
  - { name: Moom, id: 419330170 }
  # - { name: Wireless@SGx, id: 1449928544 }
