---

computername: dbmacm3
hostname: dbmacm3

finder_proxy_icon_hover_delay: 0

# safari_show_full_url_in_address_bar: true
# safari_open_safe_files_automatically: true
# safari_show_status_bar: true
# safari_show_developer_menu: true

system_save_application_state_on_quit: no
system_expand_save_panel_by_default: yes
system_expand_print_panel_by_default: yes
system_show_file_extensions_warning: no
system_warn_before_emptying_the_trash: yes
system_use_f_keys_as_standard_function_keys: yes
system_index_network_storage_with_spotlight: no
trackpad_tap_to_click: yes

screensaver_ask_for_password: no
screensaver_ask_for_password_in_seconds: 5

shell_path: /usr/local/bin/zsh

homebrew_taps:
  - cloudflare/cloudflare
  - go-task/tap
  - heroku/brew
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - hudochenkov/sshpass
  - pulumi/tap
  - spring-io/tap
#  - jeromegamez/formulae
#  - github/gh
#  - aws/tap

homebrew_apps:
  - alfred
  - alt-tab
  - anydesk
  - appcleaner
  - calibre
  - cleanmymac
  - cleanshot
  - clipy
  - cryptomator
  - discord
  - google-chrome
  - intellij-idea-ce
  - joplin
  - licecap
  - minecraft
  - netnewswire
  - onedrive
  - postico
  - postman
#  - shottr
  - slack
  - spotify
  - steam
  - temurin8
  - thunderbird
  - typora
  - visual-studio-code
  - xquartz
  - zerotier-one
#  - 1password
#  - aws-vault
#  - bartender
#  - brave-browser
#  - cardhop
#  - dash
#  - discord
#  - docker
#  - fantastical
#  - firefox
#  - fliqlo
#  - font-fira-code
#  - gpg-suite
#  - inkdrop
#  - iterm2
#  - jetbrains-toolbox
#  - lastpass
#  - mailmate
#  - moom
#  - multimc
#  - paw
#  - sequel-pro
#  - sonos
#  - spillo
#  - sublime-merge
#  - sublime-text
#  - tableplus
#  - telegram
#  - transmit
#  - twitch
#  - whatsapp
#  - yippy

homebrew_packages:
  - awscli
  - certbot
  - check-jsonschema
  - cloudflared
  - curl
  - docker
  - exercism
  - fzf
  - gh
  - git
  - gitlab-runner
  - go
  - go-task
  - gradle
  - heroku
  - jq
  - kubectl
  - lastpass-cli
  - ledger
  - m1-terraform-provider-helper
  - mas
  - maven
  - minio
  - openssh
  - pipenv
  - pulumi
  - python
  - rsync
  - shellcheck
  - spring-boot
  - sshpass
  - terraform
  - vim
  - wget
  - yazi
#  - aws-shell
#  - aws-sam-cli
#  - bash
#  - chag
#  - composer
#  - fasd
#  - httpie
#  - imagemagick
#  - make
#  - node
#  - php
#  - pkg-config
#  - tree
#  - yadm
#  - watch
#  - zlib
#  - zsh

mas_apps:
  - { name: Moom, id: 419330170 }
#  - { name: Telegram, id: 747648890 }
#  - { name: 1Blocker, id: 1107421413 }
#  - { name: Bear, id: 1091189122 }
#  - { name: Pages, id: 409201541 }
#  - { name: Patterns, id: 429449079 }
#  - { name: Tweetbot, id: 1384080005 }
